# Application Configuration
# Base: Production
# Notes:
# - Experimental features are preserved as commented sections or behind feature flags.
# - Maintains backward compatibility and production stability.

application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  # experimental_version: 3.0.0-experimental
  # experimental_mode: true

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # multi_port: [9000, 9001, 9002]  # Experimental multi-port feature

logging:
  level: INFO
  format: json
  output: /var/log/app.log
  # experimental_logging:
  #   level: TRACE
  #   format: structured
  #   output: /var/log/experimental.log
  #   ai_analysis: enabled

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  # experimental_db:
  #   host: cluster.example.com
  #   distributed: true
  #   name: devops_experimental

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # experimental_features:
  #   auto_scaling: advanced
  #   load_balancer: ai-optimized
  #   chaos_engineering: enabled

# AI/Experimental features (disabled by default)
ai_features:
  enabled: false
  # predictive_scaling: true
  # anomaly_detection: true
  # auto_optimization: true
  # model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  # - digitalocean  # experimental

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
